# Generated by Django 5.2.16 on 2026-08-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Identificador único usado en la URL (ej: historia, mision, vision)', unique=True)),
                ('imagen', models.ImageField(upload_to='institucional/')),
                ('contenido', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el menú (menor número aparece primero)')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página institucional',
                'verbose_name_plural': 'Páginas institucionales',
                'ordering': ['orden'],
            },
        ),
    ]
