# Generated by Django 5.2.16 on 2026-08-02 19:21

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginainstitucional',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
