# Generated by Django 5.2.16 on 2026-08-02 19:30

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_paginainstitucional_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginainstitucional',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
