# Generated by Django 5.2.16 on 2026-09-18 20:33

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreras', '0003_alter_carrera_campo_laboral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('foto', models.ImageField(upload_to='maestros/')),
                ('especialidad', models.CharField(help_text='Asignatura o módulo profesional que imparte', max_length=150)),
                ('semblanza', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Breve reseña profesional (opcional)', verbose_name='Semblanza')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(blank=True, help_text='Opcional: carrera a la esta asociado principalmente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maestros', to='carreras.carrera')),
            ],
            options={
                'verbose_name': 'Maestro',
                'verbose_name_plural': 'Maestros',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
