# Generated by Django 5.2.16 on 2026-09-26 16:11

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('imagen_principal', models.ImageField(upload_to='alumnos/actividades/principal/')),
                ('resumen', models.CharField(max_length=250)),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Descripcion')),
                ('fecha', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='InformacionAlumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Identificador único para la URL (ej: becas, tramites, horarios)', unique=True)),
                ('contenido', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenido')),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Opcional: documento descargable relacionado', null=True, upload_to='alumnos/documentos')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Información para alumno',
                'verbose_name_plural': 'Información para alumnos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ImagenActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='alumnos/actividades/galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='alumnos.actividad')),
            ],
            options={
                'verbose_name': 'Imagen de actividad',
                'verbose_name_plural': 'Imagenes de actividad',
                'ordering': ['orden'],
            },
        ),
    ]
