# Generated by Django 5.2.16 on 2026-08-03 19:16

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Identificador único para la URL (ej: produccion-agropecuaria)', unique=True)),
                ('imagen_principal', models.ImageField(help_text='Imagen destacada que se muestra en la tarjeta de la carrera', upload_to='carreras/principal/')),
                ('resumen', models.CharField(help_text='Descripción corta para la tarjeta en la lista de oferta educativa', max_length=250)),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ImagenCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='carreras/galeria/')),
                ('descripcion', models.CharField(blank=True, help_text='Texto alternativo o pie de foto (opcional)', max_length=150)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='carreras.carrera')),
            ],
            options={
                'verbose_name': 'Imagen de carrera',
                'verbose_name_plural': 'Imágenes de carrera',
                'ordering': ['orden'],
            },
        ),
    ]
