# Generated by Django 5.2.16 on 2026-08-11 05:22

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0002_carrera_campo_laboral_carrera_perfil_egreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='campo_laboral',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Campo Laboral'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción Carrera'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='perfil_egreso',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Perfil Egreso'),
        ),
    ]
