# Generated by Django 5.2.16 on 2026-08-04 18:48

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvocatoriaAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo_escolar', models.CharField(help_text='Ej: 2026-2027', max_length=20)),
                ('contenido', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Descripción general: proceso de registro, examen diagnóstico y resultados', null=True, verbose_name='Contenido')),
                ('fecha_inicio_registro', models.DateField()),
                ('fecha_fin_registro', models.DateField()),
                ('fecha_examen_diagnostico', models.DateField()),
                ('fecha_publicacion_resultados', models.DateField()),
                ('fecha_inicio_propedeutico', models.DateField()),
                ('convocatoria_pdf', models.FileField(help_text='Documentos de convocatoria PDF', upload_to='admision/formatos/')),
                ('formato_solicitud_pdf', models.FileField(help_text='Formato de solicitud de ingreso en PDF', upload_to='admision/formatos/')),
                ('activo', models.BooleanField(default=False, help_text='Marca solo una convocatoria como activa; será la que se muestre en el sitio')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Convocatoria de admisión',
                'verbose_name_plural': 'Convocatorias de admisión',
                'ordering': ['-fecha_inicio_registro'],
            },
        ),
        migrations.CreateModel(
            name='FichaInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(help_text='Ej: 1er semestre, 3er semestre, 5to semestre', max_length=50)),
                ('archivo', models.FileField(upload_to='admision/fichas/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_inscripcion', to='admision.convocatoriaadmision')),
            ],
            options={
                'verbose_name': 'Ficha de inscripción',
                'verbose_name_plural': 'Fichas de inscripción',
                'ordering': ['orden'],
            },
        ),
    ]
